package main

type GameInfo struct {
	Context struct {
		User struct {
			CountryCode  string `json:"countryCode"`
			CountryName  string `json:"countryName"`
			Locale       string `json:"locale"`
			TimeZone     string `json:"timeZone"`
			TimeZoneCity string `json:"timeZoneCity"`
		} `json:"user"`
		Device struct {
			Clazz interface{} `json:"clazz"`
		} `json:"device"`
	} `json:"context"`
	Error struct {
		Detail  interface{} `json:"detail"`
		IsError string      `json:"isError"`
		Message interface{} `json:"message"`
	} `json:"error"`
	Payload struct {
		League struct {
			ID   string `json:"id"`
			Name string `json:"name"`
		} `json:"league"`
		Season struct {
			IsCurrent               string `json:"isCurrent"`
			RosterSeasonType        int    `json:"rosterSeasonType"`
			RosterSeasonYear        string `json:"rosterSeasonYear"`
			RosterSeasonYearDisplay string `json:"rosterSeasonYearDisplay"`
			ScheduleSeasonType      int    `json:"scheduleSeasonType"`
			ScheduleSeasonYear      string `json:"scheduleSeasonYear"`
			ScheduleYearDisplay     string `json:"scheduleYearDisplay"`
			StatsSeasonType         int    `json:"statsSeasonType"`
			StatsSeasonYear         string `json:"statsSeasonYear"`
			StatsSeasonYearDisplay  string `json:"statsSeasonYearDisplay"`
			Year                    string `json:"year"`
			YearDisplay             string `json:"yearDisplay"`
		} `json:"season"`
		Date struct {
			Games []struct {
				Profile struct {
					ArenaLocation string      `json:"arenaLocation"`
					ArenaName     string      `json:"arenaName"`
					AwayTeamID    string      `json:"awayTeamId"`
					GameID        string      `json:"gameId"`
					HomeTeamID    string      `json:"homeTeamId"`
					Number        string      `json:"number"`
					ScheduleCode  interface{} `json:"scheduleCode"`
					SeasonType    string      `json:"seasonType"`
					Sequence      string      `json:"sequence"`
					UtcMillis     string      `json:"utcMillis"`
				} `json:"profile"`
				Boxscore struct {
					Attendance            string `json:"attendance"`
					AwayScore             int    `json:"awayScore"`
					GameLength            string `json:"gameLength"`
					HomeScore             int    `json:"homeScore"`
					OfficialsDisplayName1 string `json:"officialsDisplayName1"`
					OfficialsDisplayName2 string `json:"officialsDisplayName2"`
					OfficialsDisplayName3 string `json:"officialsDisplayName3"`
					Period                string `json:"period"`
					PeriodClock           string `json:"periodClock"`
					Status                string `json:"status"`
					StatusDesc            string `json:"statusDesc"`
					Ties                  string `json:"ties"`
				} `json:"boxscore"`
				Urls []struct {
					DisplayText string `json:"displayText"`
					Type        string `json:"type"`
					Value       string `json:"value"`
				} `json:"urls"`
				Broadcasters []interface{} `json:"broadcasters"`
				HomeTeam     struct {
					Profile struct {
						Abbr              string `json:"abbr"`
						City              string `json:"city"`
						CityEn            string `json:"cityEn"`
						Code              string `json:"code"`
						Conference        string `json:"conference"`
						DisplayAbbr       string `json:"displayAbbr"`
						DisplayConference string `json:"displayConference"`
						Division          string `json:"division"`
						ID                string `json:"id"`
						IsAllStarTeam     bool   `json:"isAllStarTeam"`
						IsLeagueTeam      bool   `json:"isLeagueTeam"`
						LeagueID          string `json:"leagueId"`
						Name              string `json:"name"`
						NameEn            string `json:"nameEn"`
					} `json:"profile"`
					Matchup struct {
						ConfRank   string      `json:"confRank"`
						DivRank    string      `json:"divRank"`
						Losses     string      `json:"losses"`
						SeriesText interface{} `json:"seriesText"`
						Wins       string      `json:"wins"`
					} `json:"matchup"`
					Score struct {
						Assists                int     `json:"assists"`
						BiggestLead            int     `json:"biggestLead"`
						Blocks                 int     `json:"blocks"`
						BlocksAgainst          int     `json:"blocksAgainst"`
						DefRebs                int     `json:"defRebs"`
						Disqualifications      int     `json:"disqualifications"`
						Ejections              int     `json:"ejections"`
						FastBreakPoints        int     `json:"fastBreakPoints"`
						Fga                    int     `json:"fga"`
						Fgm                    int     `json:"fgm"`
						Fgpct                  float64 `json:"fgpct"`
						FlagrantFouls          int     `json:"flagrantFouls"`
						Fouls                  int     `json:"fouls"`
						Fta                    int     `json:"fta"`
						Ftm                    int     `json:"ftm"`
						Ftpct                  float64 `json:"ftpct"`
						FullTimeoutsRemaining  int     `json:"fullTimeoutsRemaining"`
						Mins                   int     `json:"mins"`
						OffRebs                int     `json:"offRebs"`
						Ot10Score              int     `json:"ot10Score"`
						Ot1Score               int     `json:"ot1Score"`
						Ot2Score               int     `json:"ot2Score"`
						Ot3Score               int     `json:"ot3Score"`
						Ot4Score               int     `json:"ot4Score"`
						Ot5Score               int     `json:"ot5Score"`
						Ot6Score               int     `json:"ot6Score"`
						Ot7Score               int     `json:"ot7Score"`
						Ot8Score               int     `json:"ot8Score"`
						Ot9Score               int     `json:"ot9Score"`
						PointsInPaint          int     `json:"pointsInPaint"`
						PointsOffTurnovers     int     `json:"pointsOffTurnovers"`
						Q1Score                int     `json:"q1Score"`
						Q2Score                int     `json:"q2Score"`
						Q3Score                int     `json:"q3Score"`
						Q4Score                int     `json:"q4Score"`
						Rebs                   int     `json:"rebs"`
						Score                  int     `json:"score"`
						Seconds                int     `json:"seconds"`
						ShortTimeoutsRemaining int     `json:"shortTimeoutsRemaining"`
						Steals                 int     `json:"steals"`
						TechnicalFouls         int     `json:"technicalFouls"`
						Tpa                    int     `json:"tpa"`
						Tpm                    int     `json:"tpm"`
						Tppct                  float64 `json:"tppct"`
						Turnovers              int     `json:"turnovers"`
					} `json:"score"`
					PointGameLeader struct {
						Profile struct {
							Code               string `json:"code"`
							Country            string `json:"country"`
							DisplayAffiliation string `json:"displayAffiliation"`
							DisplayName        string `json:"displayName"`
							DisplayNameEn      string `json:"displayNameEn"`
							Dob                string `json:"dob"`
							DraftYear          string `json:"draftYear"`
							Experience         string `json:"experience"`
							FirstInitial       string `json:"firstInitial"`
							FirstName          string `json:"firstName"`
							FirstNameEn        string `json:"firstNameEn"`
							Height             string `json:"height"`
							JerseyNo           string `json:"jerseyNo"`
							LastName           string `json:"lastName"`
							LastNameEn         string `json:"lastNameEn"`
							LeagueID           string `json:"leagueId"`
							PlayerID           string `json:"playerId"`
							Position           string `json:"position"`
							SchoolType         string `json:"schoolType"`
							Weight             string `json:"weight"`
						} `json:"profile"`
						StatTotal struct {
							Assists   int     `json:"assists"`
							Blocks    int     `json:"blocks"`
							DefRebs   int     `json:"defRebs"`
							Fga       int     `json:"fga"`
							Fgm       int     `json:"fgm"`
							Fgpct     float64 `json:"fgpct"`
							Fouls     int     `json:"fouls"`
							Fta       int     `json:"fta"`
							Ftm       int     `json:"ftm"`
							Ftpct     float64 `json:"ftpct"`
							Mins      int     `json:"mins"`
							OffRebs   int     `json:"offRebs"`
							Points    int     `json:"points"`
							Rebs      int     `json:"rebs"`
							Secs      int     `json:"secs"`
							Steals    int     `json:"steals"`
							Tpa       int     `json:"tpa"`
							Tpm       int     `json:"tpm"`
							Tppct     float64 `json:"tppct"`
							Turnovers int     `json:"turnovers"`
						} `json:"statTotal"`
					} `json:"pointGameLeader"`
					AssistGameLeader struct {
						Profile struct {
							Code               string `json:"code"`
							Country            string `json:"country"`
							DisplayAffiliation string `json:"displayAffiliation"`
							DisplayName        string `json:"displayName"`
							DisplayNameEn      string `json:"displayNameEn"`
							Dob                string `json:"dob"`
							DraftYear          string `json:"draftYear"`
							Experience         string `json:"experience"`
							FirstInitial       string `json:"firstInitial"`
							FirstName          string `json:"firstName"`
							FirstNameEn        string `json:"firstNameEn"`
							Height             string `json:"height"`
							JerseyNo           string `json:"jerseyNo"`
							LastName           string `json:"lastName"`
							LastNameEn         string `json:"lastNameEn"`
							LeagueID           string `json:"leagueId"`
							PlayerID           string `json:"playerId"`
							Position           string `json:"position"`
							SchoolType         string `json:"schoolType"`
							Weight             string `json:"weight"`
						} `json:"profile"`
						StatTotal struct {
							Assists   int     `json:"assists"`
							Blocks    int     `json:"blocks"`
							DefRebs   int     `json:"defRebs"`
							Fga       int     `json:"fga"`
							Fgm       int     `json:"fgm"`
							Fgpct     float64 `json:"fgpct"`
							Fouls     int     `json:"fouls"`
							Fta       int     `json:"fta"`
							Ftm       int     `json:"ftm"`
							Ftpct     float64 `json:"ftpct"`
							Mins      int     `json:"mins"`
							OffRebs   int     `json:"offRebs"`
							Points    int     `json:"points"`
							Rebs      int     `json:"rebs"`
							Secs      int     `json:"secs"`
							Steals    int     `json:"steals"`
							Tpa       int     `json:"tpa"`
							Tpm       int     `json:"tpm"`
							Tppct     float64 `json:"tppct"`
							Turnovers int     `json:"turnovers"`
						} `json:"statTotal"`
					} `json:"assistGameLeader"`
					ReboundGameLeader struct {
						Profile struct {
							Code               string `json:"code"`
							Country            string `json:"country"`
							DisplayAffiliation string `json:"displayAffiliation"`
							DisplayName        string `json:"displayName"`
							DisplayNameEn      string `json:"displayNameEn"`
							Dob                string `json:"dob"`
							DraftYear          string `json:"draftYear"`
							Experience         string `json:"experience"`
							FirstInitial       string `json:"firstInitial"`
							FirstName          string `json:"firstName"`
							FirstNameEn        string `json:"firstNameEn"`
							Height             string `json:"height"`
							JerseyNo           string `json:"jerseyNo"`
							LastName           string `json:"lastName"`
							LastNameEn         string `json:"lastNameEn"`
							LeagueID           string `json:"leagueId"`
							PlayerID           string `json:"playerId"`
							Position           string `json:"position"`
							SchoolType         string `json:"schoolType"`
							Weight             string `json:"weight"`
						} `json:"profile"`
						StatTotal struct {
							Assists   int     `json:"assists"`
							Blocks    int     `json:"blocks"`
							DefRebs   int     `json:"defRebs"`
							Fga       int     `json:"fga"`
							Fgm       int     `json:"fgm"`
							Fgpct     float64 `json:"fgpct"`
							Fouls     int     `json:"fouls"`
							Fta       int     `json:"fta"`
							Ftm       int     `json:"ftm"`
							Ftpct     float64 `json:"ftpct"`
							Mins      int     `json:"mins"`
							OffRebs   int     `json:"offRebs"`
							Points    int     `json:"points"`
							Rebs      int     `json:"rebs"`
							Secs      int     `json:"secs"`
							Steals    int     `json:"steals"`
							Tpa       int     `json:"tpa"`
							Tpm       int     `json:"tpm"`
							Tppct     float64 `json:"tppct"`
							Turnovers int     `json:"turnovers"`
						} `json:"statTotal"`
					} `json:"reboundGameLeader"`
				} `json:"homeTeam"`
				AwayTeam struct {
					Profile struct {
						Abbr              string `json:"abbr"`
						City              string `json:"city"`
						CityEn            string `json:"cityEn"`
						Code              string `json:"code"`
						Conference        string `json:"conference"`
						DisplayAbbr       string `json:"displayAbbr"`
						DisplayConference string `json:"displayConference"`
						Division          string `json:"division"`
						ID                string `json:"id"`
						IsAllStarTeam     bool   `json:"isAllStarTeam"`
						IsLeagueTeam      bool   `json:"isLeagueTeam"`
						LeagueID          string `json:"leagueId"`
						Name              string `json:"name"`
						NameEn            string `json:"nameEn"`
					} `json:"profile"`
					Matchup struct {
						ConfRank   string      `json:"confRank"`
						DivRank    string      `json:"divRank"`
						Losses     string      `json:"losses"`
						SeriesText interface{} `json:"seriesText"`
						Wins       string      `json:"wins"`
					} `json:"matchup"`
					Score struct {
						Assists                int     `json:"assists"`
						BiggestLead            int     `json:"biggestLead"`
						Blocks                 int     `json:"blocks"`
						BlocksAgainst          int     `json:"blocksAgainst"`
						DefRebs                int     `json:"defRebs"`
						Disqualifications      int     `json:"disqualifications"`
						Ejections              int     `json:"ejections"`
						FastBreakPoints        int     `json:"fastBreakPoints"`
						Fga                    int     `json:"fga"`
						Fgm                    int     `json:"fgm"`
						Fgpct                  float64 `json:"fgpct"`
						FlagrantFouls          int     `json:"flagrantFouls"`
						Fouls                  int     `json:"fouls"`
						Fta                    int     `json:"fta"`
						Ftm                    int     `json:"ftm"`
						Ftpct                  float64 `json:"ftpct"`
						FullTimeoutsRemaining  int     `json:"fullTimeoutsRemaining"`
						Mins                   int     `json:"mins"`
						OffRebs                int     `json:"offRebs"`
						Ot10Score              int     `json:"ot10Score"`
						Ot1Score               int     `json:"ot1Score"`
						Ot2Score               int     `json:"ot2Score"`
						Ot3Score               int     `json:"ot3Score"`
						Ot4Score               int     `json:"ot4Score"`
						Ot5Score               int     `json:"ot5Score"`
						Ot6Score               int     `json:"ot6Score"`
						Ot7Score               int     `json:"ot7Score"`
						Ot8Score               int     `json:"ot8Score"`
						Ot9Score               int     `json:"ot9Score"`
						PointsInPaint          int     `json:"pointsInPaint"`
						PointsOffTurnovers     int     `json:"pointsOffTurnovers"`
						Q1Score                int     `json:"q1Score"`
						Q2Score                int     `json:"q2Score"`
						Q3Score                int     `json:"q3Score"`
						Q4Score                int     `json:"q4Score"`
						Rebs                   int     `json:"rebs"`
						Score                  int     `json:"score"`
						Seconds                int     `json:"seconds"`
						ShortTimeoutsRemaining int     `json:"shortTimeoutsRemaining"`
						Steals                 int     `json:"steals"`
						TechnicalFouls         int     `json:"technicalFouls"`
						Tpa                    int     `json:"tpa"`
						Tpm                    int     `json:"tpm"`
						Tppct                  float64 `json:"tppct"`
						Turnovers              int     `json:"turnovers"`
					} `json:"score"`
					PointGameLeader struct {
						Profile struct {
							Code               string `json:"code"`
							Country            string `json:"country"`
							DisplayAffiliation string `json:"displayAffiliation"`
							DisplayName        string `json:"displayName"`
							DisplayNameEn      string `json:"displayNameEn"`
							Dob                string `json:"dob"`
							DraftYear          string `json:"draftYear"`
							Experience         string `json:"experience"`
							FirstInitial       string `json:"firstInitial"`
							FirstName          string `json:"firstName"`
							FirstNameEn        string `json:"firstNameEn"`
							Height             string `json:"height"`
							JerseyNo           string `json:"jerseyNo"`
							LastName           string `json:"lastName"`
							LastNameEn         string `json:"lastNameEn"`
							LeagueID           string `json:"leagueId"`
							PlayerID           string `json:"playerId"`
							Position           string `json:"position"`
							SchoolType         string `json:"schoolType"`
							Weight             string `json:"weight"`
						} `json:"profile"`
						StatTotal struct {
							Assists   int     `json:"assists"`
							Blocks    int     `json:"blocks"`
							DefRebs   int     `json:"defRebs"`
							Fga       int     `json:"fga"`
							Fgm       int     `json:"fgm"`
							Fgpct     float64 `json:"fgpct"`
							Fouls     int     `json:"fouls"`
							Fta       int     `json:"fta"`
							Ftm       int     `json:"ftm"`
							Ftpct     float64 `json:"ftpct"`
							Mins      int     `json:"mins"`
							OffRebs   int     `json:"offRebs"`
							Points    int     `json:"points"`
							Rebs      int     `json:"rebs"`
							Secs      int     `json:"secs"`
							Steals    int     `json:"steals"`
							Tpa       int     `json:"tpa"`
							Tpm       int     `json:"tpm"`
							Tppct     float64 `json:"tppct"`
							Turnovers int     `json:"turnovers"`
						} `json:"statTotal"`
					} `json:"pointGameLeader"`
					AssistGameLeader struct {
						Profile struct {
							Code               string `json:"code"`
							Country            string `json:"country"`
							DisplayAffiliation string `json:"displayAffiliation"`
							DisplayName        string `json:"displayName"`
							DisplayNameEn      string `json:"displayNameEn"`
							Dob                string `json:"dob"`
							DraftYear          string `json:"draftYear"`
							Experience         string `json:"experience"`
							FirstInitial       string `json:"firstInitial"`
							FirstName          string `json:"firstName"`
							FirstNameEn        string `json:"firstNameEn"`
							Height             string `json:"height"`
							JerseyNo           string `json:"jerseyNo"`
							LastName           string `json:"lastName"`
							LastNameEn         string `json:"lastNameEn"`
							LeagueID           string `json:"leagueId"`
							PlayerID           string `json:"playerId"`
							Position           string `json:"position"`
							SchoolType         string `json:"schoolType"`
							Weight             string `json:"weight"`
						} `json:"profile"`
						StatTotal struct {
							Assists   int     `json:"assists"`
							Blocks    int     `json:"blocks"`
							DefRebs   int     `json:"defRebs"`
							Fga       int     `json:"fga"`
							Fgm       int     `json:"fgm"`
							Fgpct     float64 `json:"fgpct"`
							Fouls     int     `json:"fouls"`
							Fta       int     `json:"fta"`
							Ftm       int     `json:"ftm"`
							Ftpct     float64 `json:"ftpct"`
							Mins      int     `json:"mins"`
							OffRebs   int     `json:"offRebs"`
							Points    int     `json:"points"`
							Rebs      int     `json:"rebs"`
							Secs      int     `json:"secs"`
							Steals    int     `json:"steals"`
							Tpa       int     `json:"tpa"`
							Tpm       int     `json:"tpm"`
							Tppct     float64 `json:"tppct"`
							Turnovers int     `json:"turnovers"`
						} `json:"statTotal"`
					} `json:"assistGameLeader"`
					ReboundGameLeader struct {
						Profile struct {
							Code               string `json:"code"`
							Country            string `json:"country"`
							DisplayAffiliation string `json:"displayAffiliation"`
							DisplayName        string `json:"displayName"`
							DisplayNameEn      string `json:"displayNameEn"`
							Dob                string `json:"dob"`
							DraftYear          string `json:"draftYear"`
							Experience         string `json:"experience"`
							FirstInitial       string `json:"firstInitial"`
							FirstName          string `json:"firstName"`
							FirstNameEn        string `json:"firstNameEn"`
							Height             string `json:"height"`
							JerseyNo           string `json:"jerseyNo"`
							LastName           string `json:"lastName"`
							LastNameEn         string `json:"lastNameEn"`
							LeagueID           string `json:"leagueId"`
							PlayerID           string `json:"playerId"`
							Position           string `json:"position"`
							SchoolType         string `json:"schoolType"`
							Weight             string `json:"weight"`
						} `json:"profile"`
						StatTotal struct {
							Assists   int     `json:"assists"`
							Blocks    int     `json:"blocks"`
							DefRebs   int     `json:"defRebs"`
							Fga       int     `json:"fga"`
							Fgm       int     `json:"fgm"`
							Fgpct     float64 `json:"fgpct"`
							Fouls     int     `json:"fouls"`
							Fta       int     `json:"fta"`
							Ftm       int     `json:"ftm"`
							Ftpct     float64 `json:"ftpct"`
							Mins      int     `json:"mins"`
							OffRebs   int     `json:"offRebs"`
							Points    int     `json:"points"`
							Rebs      int     `json:"rebs"`
							Secs      int     `json:"secs"`
							Steals    int     `json:"steals"`
							Tpa       int     `json:"tpa"`
							Tpm       int     `json:"tpm"`
							Tppct     float64 `json:"tppct"`
							Turnovers int     `json:"turnovers"`
						} `json:"statTotal"`
					} `json:"reboundGameLeader"`
				} `json:"awayTeam"`
			} `json:"games"`
			DateMillis string `json:"dateMillis"`
			GameCount  string `json:"gameCount"`
		} `json:"date"`
		NextAvailableDateMillis string `json:"nextAvailableDateMillis"`
		UtcMillis               string `json:"utcMillis"`
	} `json:"payload"`
	Timestamp string `json:"timestamp"`
}

type GamePlayerInfo struct {
	Context struct {
		User struct {
			CountryCode  string `json:"countryCode"`
			CountryName  string `json:"countryName"`
			Locale       string `json:"locale"`
			TimeZone     string `json:"timeZone"`
			TimeZoneCity string `json:"timeZoneCity"`
		} `json:"user"`
		Device struct {
			Clazz interface{} `json:"clazz"`
		} `json:"device"`
	} `json:"context"`
	Error struct {
		Detail  interface{} `json:"detail"`
		IsError string      `json:"isError"`
		Message interface{} `json:"message"`
	} `json:"error"`
	Payload struct {
		League struct {
			ID   string `json:"id"`
			Name string `json:"name"`
		} `json:"league"`
		Season struct {
			IsCurrent               string `json:"isCurrent"`
			RosterSeasonType        int    `json:"rosterSeasonType"`
			RosterSeasonYear        string `json:"rosterSeasonYear"`
			RosterSeasonYearDisplay string `json:"rosterSeasonYearDisplay"`
			ScheduleSeasonType      int    `json:"scheduleSeasonType"`
			ScheduleSeasonYear      string `json:"scheduleSeasonYear"`
			ScheduleYearDisplay     string `json:"scheduleYearDisplay"`
			StatsSeasonType         int    `json:"statsSeasonType"`
			StatsSeasonYear         string `json:"statsSeasonYear"`
			StatsSeasonYearDisplay  string `json:"statsSeasonYearDisplay"`
			Year                    string `json:"year"`
			YearDisplay             string `json:"yearDisplay"`
		} `json:"season"`
		GameProfile struct {
			ArenaLocation string      `json:"arenaLocation"`
			ArenaName     string      `json:"arenaName"`
			AwayTeamID    string      `json:"awayTeamId"`
			GameID        string      `json:"gameId"`
			HomeTeamID    string      `json:"homeTeamId"`
			Number        string      `json:"number"`
			ScheduleCode  interface{} `json:"scheduleCode"`
			SeasonType    string      `json:"seasonType"`
			Sequence      string      `json:"sequence"`
			UtcMillis     string      `json:"utcMillis"`
		} `json:"gameProfile"`
		Boxscore struct {
			Attendance            string `json:"attendance"`
			AwayScore             int    `json:"awayScore"`
			GameLength            string `json:"gameLength"`
			HomeScore             int    `json:"homeScore"`
			OfficialsDisplayName1 string `json:"officialsDisplayName1"`
			OfficialsDisplayName2 string `json:"officialsDisplayName2"`
			OfficialsDisplayName3 string `json:"officialsDisplayName3"`
			Period                string `json:"period"`
			PeriodClock           string `json:"periodClock"`
			Status                string `json:"status"`
			StatusDesc            string `json:"statusDesc"`
			Ties                  string `json:"ties"`
		} `json:"boxscore"`
		Urls []struct {
			DisplayText string `json:"displayText"`
			Type        string `json:"type"`
			Value       string `json:"value"`
		} `json:"urls"`
		Broadcasters []struct {
			ID    string      `json:"id"`
			Media string      `json:"media"`
			Name  string      `json:"name"`
			Range interface{} `json:"range"`
			Type  string      `json:"type"`
			URL   interface{} `json:"url"`
		} `json:"broadcasters"`
		HomeTeam struct {
			Profile struct {
				Abbr              string `json:"abbr"`
				City              string `json:"city"`
				CityEn            string `json:"cityEn"`
				Code              string `json:"code"`
				Conference        string `json:"conference"`
				DisplayAbbr       string `json:"displayAbbr"`
				DisplayConference string `json:"displayConference"`
				Division          string `json:"division"`
				ID                string `json:"id"`
				IsAllStarTeam     bool   `json:"isAllStarTeam"`
				IsLeagueTeam      bool   `json:"isLeagueTeam"`
				LeagueID          string `json:"leagueId"`
				Name              string `json:"name"`
				NameEn            string `json:"nameEn"`
			} `json:"profile"`
			Standing struct {
				Clinched    interface{} `json:"clinched"`
				ConfRank    int         `json:"confRank"`
				DivRank     int         `json:"divRank"`
				Last10      string      `json:"last10"`
				Losses      int         `json:"losses"`
				OnHotStreak string      `json:"onHotStreak"`
				Streak      string      `json:"streak"`
				Wins        int         `json:"wins"`
			} `json:"standing"`
			Score struct {
				Assists                int     `json:"assists"`
				BiggestLead            int     `json:"biggestLead"`
				Blocks                 int     `json:"blocks"`
				BlocksAgainst          int     `json:"blocksAgainst"`
				DefRebs                int     `json:"defRebs"`
				Disqualifications      int     `json:"disqualifications"`
				Ejections              int     `json:"ejections"`
				FastBreakPoints        int     `json:"fastBreakPoints"`
				Fga                    int     `json:"fga"`
				Fgm                    int     `json:"fgm"`
				Fgpct                  float64 `json:"fgpct"`
				FlagrantFouls          int     `json:"flagrantFouls"`
				Fouls                  int     `json:"fouls"`
				Fta                    int     `json:"fta"`
				Ftm                    int     `json:"ftm"`
				Ftpct                  float64 `json:"ftpct"`
				FullTimeoutsRemaining  int     `json:"fullTimeoutsRemaining"`
				Mins                   int     `json:"mins"`
				OffRebs                int     `json:"offRebs"`
				Ot10Score              int     `json:"ot10Score"`
				Ot1Score               int     `json:"ot1Score"`
				Ot2Score               int     `json:"ot2Score"`
				Ot3Score               int     `json:"ot3Score"`
				Ot4Score               int     `json:"ot4Score"`
				Ot5Score               int     `json:"ot5Score"`
				Ot6Score               int     `json:"ot6Score"`
				Ot7Score               int     `json:"ot7Score"`
				Ot8Score               int     `json:"ot8Score"`
				Ot9Score               int     `json:"ot9Score"`
				PointsInPaint          int     `json:"pointsInPaint"`
				PointsOffTurnovers     int     `json:"pointsOffTurnovers"`
				Q1Score                int     `json:"q1Score"`
				Q2Score                int     `json:"q2Score"`
				Q3Score                int     `json:"q3Score"`
				Q4Score                int     `json:"q4Score"`
				Rebs                   int     `json:"rebs"`
				Score                  int     `json:"score"`
				Seconds                int     `json:"seconds"`
				ShortTimeoutsRemaining int     `json:"shortTimeoutsRemaining"`
				Steals                 int     `json:"steals"`
				TechnicalFouls         int     `json:"technicalFouls"`
				Tpa                    int     `json:"tpa"`
				Tpm                    int     `json:"tpm"`
				Tppct                  float64 `json:"tppct"`
				Turnovers              int     `json:"turnovers"`
			} `json:"score"`
			Matchup struct {
				ConfRank   string      `json:"confRank"`
				DivRank    string      `json:"divRank"`
				Losses     string      `json:"losses"`
				SeriesText interface{} `json:"seriesText"`
				Wins       string      `json:"wins"`
			} `json:"matchup"`
			GamePlayers []struct {
				Profile struct {
					Code               string `json:"code"`
					Country            string `json:"country"`
					DisplayAffiliation string `json:"displayAffiliation"`
					DisplayName        string `json:"displayName"`
					DisplayNameEn      string `json:"displayNameEn"`
					Dob                string `json:"dob"`
					DraftYear          string `json:"draftYear"`
					Experience         string `json:"experience"`
					FirstInitial       string `json:"firstInitial"`
					FirstName          string `json:"firstName"`
					FirstNameEn        string `json:"firstNameEn"`
					Height             string `json:"height"`
					JerseyNo           string `json:"jerseyNo"`
					LastName           string `json:"lastName"`
					LastNameEn         string `json:"lastNameEn"`
					LeagueID           string `json:"leagueId"`
					PlayerID           string `json:"playerId"`
					Position           string `json:"position"`
					SchoolType         string `json:"schoolType"`
					Weight             string `json:"weight"`
				} `json:"profile"`
				Boxscore struct {
					DnpReason string `json:"dnpReason"`
					IsStarter string `json:"isStarter"`
					OnCourt   string `json:"onCourt"`
					Order     int    `json:"order"`
					PlusMinus string `json:"plusMinus"`
					Position  string `json:"position"`
				} `json:"boxscore"`
				StatTotal struct {
					Assists   int     `json:"assists"`
					Blocks    int     `json:"blocks"`
					DefRebs   int     `json:"defRebs"`
					Fga       int     `json:"fga"`
					Fgm       int     `json:"fgm"`
					Fgpct     float64 `json:"fgpct"`
					Fouls     int     `json:"fouls"`
					Fta       int     `json:"fta"`
					Ftm       int     `json:"ftm"`
					Ftpct     float64 `json:"ftpct"`
					Mins      int     `json:"mins"`
					OffRebs   int     `json:"offRebs"`
					Points    int     `json:"points"`
					Rebs      int     `json:"rebs"`
					Secs      int     `json:"secs"`
					Steals    int     `json:"steals"`
					Tpa       int     `json:"tpa"`
					Tpm       int     `json:"tpm"`
					Tppct     float64 `json:"tppct"`
					Turnovers int     `json:"turnovers"`
				} `json:"statTotal"`
			} `json:"gamePlayers"`
			PointGameLeader struct {
				Profile struct {
					Code               string `json:"code"`
					Country            string `json:"country"`
					DisplayAffiliation string `json:"displayAffiliation"`
					DisplayName        string `json:"displayName"`
					DisplayNameEn      string `json:"displayNameEn"`
					Dob                string `json:"dob"`
					DraftYear          string `json:"draftYear"`
					Experience         string `json:"experience"`
					FirstInitial       string `json:"firstInitial"`
					FirstName          string `json:"firstName"`
					FirstNameEn        string `json:"firstNameEn"`
					Height             string `json:"height"`
					JerseyNo           string `json:"jerseyNo"`
					LastName           string `json:"lastName"`
					LastNameEn         string `json:"lastNameEn"`
					LeagueID           string `json:"leagueId"`
					PlayerID           string `json:"playerId"`
					Position           string `json:"position"`
					SchoolType         string `json:"schoolType"`
					Weight             string `json:"weight"`
				} `json:"profile"`
				StatTotal struct {
					Assists   int     `json:"assists"`
					Blocks    int     `json:"blocks"`
					DefRebs   int     `json:"defRebs"`
					Fga       int     `json:"fga"`
					Fgm       int     `json:"fgm"`
					Fgpct     float64 `json:"fgpct"`
					Fouls     int     `json:"fouls"`
					Fta       int     `json:"fta"`
					Ftm       int     `json:"ftm"`
					Ftpct     float64 `json:"ftpct"`
					Mins      int     `json:"mins"`
					OffRebs   int     `json:"offRebs"`
					Points    int     `json:"points"`
					Rebs      int     `json:"rebs"`
					Secs      int     `json:"secs"`
					Steals    int     `json:"steals"`
					Tpa       int     `json:"tpa"`
					Tpm       int     `json:"tpm"`
					Tppct     float64 `json:"tppct"`
					Turnovers int     `json:"turnovers"`
				} `json:"statTotal"`
			} `json:"pointGameLeader"`
			AssistGameLeader struct {
				Profile struct {
					Code               string `json:"code"`
					Country            string `json:"country"`
					DisplayAffiliation string `json:"displayAffiliation"`
					DisplayName        string `json:"displayName"`
					DisplayNameEn      string `json:"displayNameEn"`
					Dob                string `json:"dob"`
					DraftYear          string `json:"draftYear"`
					Experience         string `json:"experience"`
					FirstInitial       string `json:"firstInitial"`
					FirstName          string `json:"firstName"`
					FirstNameEn        string `json:"firstNameEn"`
					Height             string `json:"height"`
					JerseyNo           string `json:"jerseyNo"`
					LastName           string `json:"lastName"`
					LastNameEn         string `json:"lastNameEn"`
					LeagueID           string `json:"leagueId"`
					PlayerID           string `json:"playerId"`
					Position           string `json:"position"`
					SchoolType         string `json:"schoolType"`
					Weight             string `json:"weight"`
				} `json:"profile"`
				StatTotal struct {
					Assists   int     `json:"assists"`
					Blocks    int     `json:"blocks"`
					DefRebs   int     `json:"defRebs"`
					Fga       int     `json:"fga"`
					Fgm       int     `json:"fgm"`
					Fgpct     float64 `json:"fgpct"`
					Fouls     int     `json:"fouls"`
					Fta       int     `json:"fta"`
					Ftm       int     `json:"ftm"`
					Ftpct     float64 `json:"ftpct"`
					Mins      int     `json:"mins"`
					OffRebs   int     `json:"offRebs"`
					Points    int     `json:"points"`
					Rebs      int     `json:"rebs"`
					Secs      int     `json:"secs"`
					Steals    int     `json:"steals"`
					Tpa       int     `json:"tpa"`
					Tpm       int     `json:"tpm"`
					Tppct     float64 `json:"tppct"`
					Turnovers int     `json:"turnovers"`
				} `json:"statTotal"`
			} `json:"assistGameLeader"`
			ReboundGameLeader struct {
				Profile struct {
					Code               string `json:"code"`
					Country            string `json:"country"`
					DisplayAffiliation string `json:"displayAffiliation"`
					DisplayName        string `json:"displayName"`
					DisplayNameEn      string `json:"displayNameEn"`
					Dob                string `json:"dob"`
					DraftYear          string `json:"draftYear"`
					Experience         string `json:"experience"`
					FirstInitial       string `json:"firstInitial"`
					FirstName          string `json:"firstName"`
					FirstNameEn        string `json:"firstNameEn"`
					Height             string `json:"height"`
					JerseyNo           string `json:"jerseyNo"`
					LastName           string `json:"lastName"`
					LastNameEn         string `json:"lastNameEn"`
					LeagueID           string `json:"leagueId"`
					PlayerID           string `json:"playerId"`
					Position           string `json:"position"`
					SchoolType         string `json:"schoolType"`
					Weight             string `json:"weight"`
				} `json:"profile"`
				StatTotal struct {
					Assists   int     `json:"assists"`
					Blocks    int     `json:"blocks"`
					DefRebs   int     `json:"defRebs"`
					Fga       int     `json:"fga"`
					Fgm       int     `json:"fgm"`
					Fgpct     float64 `json:"fgpct"`
					Fouls     int     `json:"fouls"`
					Fta       int     `json:"fta"`
					Ftm       int     `json:"ftm"`
					Ftpct     float64 `json:"ftpct"`
					Mins      int     `json:"mins"`
					OffRebs   int     `json:"offRebs"`
					Points    int     `json:"points"`
					Rebs      int     `json:"rebs"`
					Secs      int     `json:"secs"`
					Steals    int     `json:"steals"`
					Tpa       int     `json:"tpa"`
					Tpm       int     `json:"tpm"`
					Tppct     float64 `json:"tppct"`
					Turnovers int     `json:"turnovers"`
				} `json:"statTotal"`
			} `json:"reboundGameLeader"`
			PointSeasonLeader struct {
				Profile struct {
					Code               string `json:"code"`
					Country            string `json:"country"`
					DisplayAffiliation string `json:"displayAffiliation"`
					DisplayName        string `json:"displayName"`
					DisplayNameEn      string `json:"displayNameEn"`
					Dob                string `json:"dob"`
					DraftYear          string `json:"draftYear"`
					Experience         string `json:"experience"`
					FirstInitial       string `json:"firstInitial"`
					FirstName          string `json:"firstName"`
					FirstNameEn        string `json:"firstNameEn"`
					Height             string `json:"height"`
					JerseyNo           string `json:"jerseyNo"`
					LastName           string `json:"lastName"`
					LastNameEn         string `json:"lastNameEn"`
					LeagueID           string `json:"leagueId"`
					PlayerID           string `json:"playerId"`
					Position           string `json:"position"`
					SchoolType         string `json:"schoolType"`
					Weight             string `json:"weight"`
				} `json:"profile"`
				StatAverage struct {
					AssistsPg    float64 `json:"assistsPg"`
					BlocksPg     float64 `json:"blocksPg"`
					DefRebsPg    float64 `json:"defRebsPg"`
					Efficiency   float64 `json:"efficiency"`
					FgaPg        float64 `json:"fgaPg"`
					FgmPg        float64 `json:"fgmPg"`
					Fgpct        float64 `json:"fgpct"`
					FoulsPg      float64 `json:"foulsPg"`
					FtaPg        float64 `json:"ftaPg"`
					FtmPg        float64 `json:"ftmPg"`
					Ftpct        float64 `json:"ftpct"`
					Games        int     `json:"games"`
					GamesStarted int     `json:"gamesStarted"`
					MinsPg       float64 `json:"minsPg"`
					OffRebsPg    float64 `json:"offRebsPg"`
					PointsPg     float64 `json:"pointsPg"`
					RebsPg       float64 `json:"rebsPg"`
					StealsPg     float64 `json:"stealsPg"`
					TpaPg        float64 `json:"tpaPg"`
					TpmPg        float64 `json:"tpmPg"`
					Tppct        float64 `json:"tppct"`
					TurnoversPg  float64 `json:"turnoversPg"`
				} `json:"statAverage"`
			} `json:"pointSeasonLeader"`
			AssistSeasonLeader struct {
				Profile struct {
					Code               string `json:"code"`
					Country            string `json:"country"`
					DisplayAffiliation string `json:"displayAffiliation"`
					DisplayName        string `json:"displayName"`
					DisplayNameEn      string `json:"displayNameEn"`
					Dob                string `json:"dob"`
					DraftYear          string `json:"draftYear"`
					Experience         string `json:"experience"`
					FirstInitial       string `json:"firstInitial"`
					FirstName          string `json:"firstName"`
					FirstNameEn        string `json:"firstNameEn"`
					Height             string `json:"height"`
					JerseyNo           string `json:"jerseyNo"`
					LastName           string `json:"lastName"`
					LastNameEn         string `json:"lastNameEn"`
					LeagueID           string `json:"leagueId"`
					PlayerID           string `json:"playerId"`
					Position           string `json:"position"`
					SchoolType         string `json:"schoolType"`
					Weight             string `json:"weight"`
				} `json:"profile"`
				StatAverage struct {
					AssistsPg    float64 `json:"assistsPg"`
					BlocksPg     float64 `json:"blocksPg"`
					DefRebsPg    float64 `json:"defRebsPg"`
					Efficiency   float64 `json:"efficiency"`
					FgaPg        float64 `json:"fgaPg"`
					FgmPg        float64 `json:"fgmPg"`
					Fgpct        float64 `json:"fgpct"`
					FoulsPg      float64 `json:"foulsPg"`
					FtaPg        float64 `json:"ftaPg"`
					FtmPg        float64 `json:"ftmPg"`
					Ftpct        float64 `json:"ftpct"`
					Games        int     `json:"games"`
					GamesStarted int     `json:"gamesStarted"`
					MinsPg       float64 `json:"minsPg"`
					OffRebsPg    float64 `json:"offRebsPg"`
					PointsPg     float64 `json:"pointsPg"`
					RebsPg       float64 `json:"rebsPg"`
					StealsPg     float64 `json:"stealsPg"`
					TpaPg        float64 `json:"tpaPg"`
					TpmPg        float64 `json:"tpmPg"`
					Tppct        float64 `json:"tppct"`
					TurnoversPg  float64 `json:"turnoversPg"`
				} `json:"statAverage"`
			} `json:"assistSeasonLeader"`
			ReboundSeasonLeader struct {
				Profile struct {
					Code               string `json:"code"`
					Country            string `json:"country"`
					DisplayAffiliation string `json:"displayAffiliation"`
					DisplayName        string `json:"displayName"`
					DisplayNameEn      string `json:"displayNameEn"`
					Dob                string `json:"dob"`
					DraftYear          string `json:"draftYear"`
					Experience         string `json:"experience"`
					FirstInitial       string `json:"firstInitial"`
					FirstName          string `json:"firstName"`
					FirstNameEn        string `json:"firstNameEn"`
					Height             string `json:"height"`
					JerseyNo           string `json:"jerseyNo"`
					LastName           string `json:"lastName"`
					LastNameEn         string `json:"lastNameEn"`
					LeagueID           string `json:"leagueId"`
					PlayerID           string `json:"playerId"`
					Position           string `json:"position"`
					SchoolType         string `json:"schoolType"`
					Weight             string `json:"weight"`
				} `json:"profile"`
				StatAverage struct {
					AssistsPg    float64 `json:"assistsPg"`
					BlocksPg     float64 `json:"blocksPg"`
					DefRebsPg    float64 `json:"defRebsPg"`
					Efficiency   float64 `json:"efficiency"`
					FgaPg        float64 `json:"fgaPg"`
					FgmPg        float64 `json:"fgmPg"`
					Fgpct        float64 `json:"fgpct"`
					FoulsPg      float64 `json:"foulsPg"`
					FtaPg        float64 `json:"ftaPg"`
					FtmPg        float64 `json:"ftmPg"`
					Ftpct        float64 `json:"ftpct"`
					Games        int     `json:"games"`
					GamesStarted int     `json:"gamesStarted"`
					MinsPg       float64 `json:"minsPg"`
					OffRebsPg    float64 `json:"offRebsPg"`
					PointsPg     float64 `json:"pointsPg"`
					RebsPg       float64 `json:"rebsPg"`
					StealsPg     float64 `json:"stealsPg"`
					TpaPg        float64 `json:"tpaPg"`
					TpmPg        float64 `json:"tpmPg"`
					Tppct        float64 `json:"tppct"`
					TurnoversPg  float64 `json:"turnoversPg"`
				} `json:"statAverage"`
			} `json:"reboundSeasonLeader"`
		} `json:"homeTeam"`
		AwayTeam struct {
			Profile struct {
				Abbr              string `json:"abbr"`
				City              string `json:"city"`
				CityEn            string `json:"cityEn"`
				Code              string `json:"code"`
				Conference        string `json:"conference"`
				DisplayAbbr       string `json:"displayAbbr"`
				DisplayConference string `json:"displayConference"`
				Division          string `json:"division"`
				ID                string `json:"id"`
				IsAllStarTeam     bool   `json:"isAllStarTeam"`
				IsLeagueTeam      bool   `json:"isLeagueTeam"`
				LeagueID          string `json:"leagueId"`
				Name              string `json:"name"`
				NameEn            string `json:"nameEn"`
			} `json:"profile"`
			Standing struct {
				Clinched    interface{} `json:"clinched"`
				ConfRank    int         `json:"confRank"`
				DivRank     int         `json:"divRank"`
				Last10      string      `json:"last10"`
				Losses      int         `json:"losses"`
				OnHotStreak string      `json:"onHotStreak"`
				Streak      string      `json:"streak"`
				Wins        int         `json:"wins"`
			} `json:"standing"`
			Score struct {
				Assists                int     `json:"assists"`
				BiggestLead            int     `json:"biggestLead"`
				Blocks                 int     `json:"blocks"`
				BlocksAgainst          int     `json:"blocksAgainst"`
				DefRebs                int     `json:"defRebs"`
				Disqualifications      int     `json:"disqualifications"`
				Ejections              int     `json:"ejections"`
				FastBreakPoints        int     `json:"fastBreakPoints"`
				Fga                    int     `json:"fga"`
				Fgm                    int     `json:"fgm"`
				Fgpct                  float64 `json:"fgpct"`
				FlagrantFouls          int     `json:"flagrantFouls"`
				Fouls                  int     `json:"fouls"`
				Fta                    int     `json:"fta"`
				Ftm                    int     `json:"ftm"`
				Ftpct                  float64 `json:"ftpct"`
				FullTimeoutsRemaining  int     `json:"fullTimeoutsRemaining"`
				Mins                   int     `json:"mins"`
				OffRebs                int     `json:"offRebs"`
				Ot10Score              int     `json:"ot10Score"`
				Ot1Score               int     `json:"ot1Score"`
				Ot2Score               int     `json:"ot2Score"`
				Ot3Score               int     `json:"ot3Score"`
				Ot4Score               int     `json:"ot4Score"`
				Ot5Score               int     `json:"ot5Score"`
				Ot6Score               int     `json:"ot6Score"`
				Ot7Score               int     `json:"ot7Score"`
				Ot8Score               int     `json:"ot8Score"`
				Ot9Score               int     `json:"ot9Score"`
				PointsInPaint          int     `json:"pointsInPaint"`
				PointsOffTurnovers     int     `json:"pointsOffTurnovers"`
				Q1Score                int     `json:"q1Score"`
				Q2Score                int     `json:"q2Score"`
				Q3Score                int     `json:"q3Score"`
				Q4Score                int     `json:"q4Score"`
				Rebs                   int     `json:"rebs"`
				Score                  int     `json:"score"`
				Seconds                int     `json:"seconds"`
				ShortTimeoutsRemaining int     `json:"shortTimeoutsRemaining"`
				Steals                 int     `json:"steals"`
				TechnicalFouls         int     `json:"technicalFouls"`
				Tpa                    int     `json:"tpa"`
				Tpm                    int     `json:"tpm"`
				Tppct                  float64 `json:"tppct"`
				Turnovers              int     `json:"turnovers"`
			} `json:"score"`
			Matchup struct {
				ConfRank   string      `json:"confRank"`
				DivRank    string      `json:"divRank"`
				Losses     string      `json:"losses"`
				SeriesText interface{} `json:"seriesText"`
				Wins       string      `json:"wins"`
			} `json:"matchup"`
			GamePlayers []struct {
				Profile struct {
					Code               string `json:"code"`
					Country            string `json:"country"`
					DisplayAffiliation string `json:"displayAffiliation"`
					DisplayName        string `json:"displayName"`
					DisplayNameEn      string `json:"displayNameEn"`
					Dob                string `json:"dob"`
					DraftYear          string `json:"draftYear"`
					Experience         string `json:"experience"`
					FirstInitial       string `json:"firstInitial"`
					FirstName          string `json:"firstName"`
					FirstNameEn        string `json:"firstNameEn"`
					Height             string `json:"height"`
					JerseyNo           string `json:"jerseyNo"`
					LastName           string `json:"lastName"`
					LastNameEn         string `json:"lastNameEn"`
					LeagueID           string `json:"leagueId"`
					PlayerID           string `json:"playerId"`
					Position           string `json:"position"`
					SchoolType         string `json:"schoolType"`
					Weight             string `json:"weight"`
				} `json:"profile"`
				Boxscore struct {
					DnpReason string `json:"dnpReason"`
					IsStarter string `json:"isStarter"`
					OnCourt   string `json:"onCourt"`
					Order     int    `json:"order"`
					PlusMinus string `json:"plusMinus"`
					Position  string `json:"position"`
				} `json:"boxscore"`
				StatTotal struct {
					Assists   int     `json:"assists"`
					Blocks    int     `json:"blocks"`
					DefRebs   int     `json:"defRebs"`
					Fga       int     `json:"fga"`
					Fgm       int     `json:"fgm"`
					Fgpct     float64 `json:"fgpct"`
					Fouls     int     `json:"fouls"`
					Fta       int     `json:"fta"`
					Ftm       int     `json:"ftm"`
					Ftpct     float64 `json:"ftpct"`
					Mins      int     `json:"mins"`
					OffRebs   int     `json:"offRebs"`
					Points    int     `json:"points"`
					Rebs      int     `json:"rebs"`
					Secs      int     `json:"secs"`
					Steals    int     `json:"steals"`
					Tpa       int     `json:"tpa"`
					Tpm       int     `json:"tpm"`
					Tppct     float64 `json:"tppct"`
					Turnovers int     `json:"turnovers"`
				} `json:"statTotal"`
			} `json:"gamePlayers"`
			PointGameLeader struct {
				Profile struct {
					Code               string `json:"code"`
					Country            string `json:"country"`
					DisplayAffiliation string `json:"displayAffiliation"`
					DisplayName        string `json:"displayName"`
					DisplayNameEn      string `json:"displayNameEn"`
					Dob                string `json:"dob"`
					DraftYear          string `json:"draftYear"`
					Experience         string `json:"experience"`
					FirstInitial       string `json:"firstInitial"`
					FirstName          string `json:"firstName"`
					FirstNameEn        string `json:"firstNameEn"`
					Height             string `json:"height"`
					JerseyNo           string `json:"jerseyNo"`
					LastName           string `json:"lastName"`
					LastNameEn         string `json:"lastNameEn"`
					LeagueID           string `json:"leagueId"`
					PlayerID           string `json:"playerId"`
					Position           string `json:"position"`
					SchoolType         string `json:"schoolType"`
					Weight             string `json:"weight"`
				} `json:"profile"`
				StatTotal struct {
					Assists   int     `json:"assists"`
					Blocks    int     `json:"blocks"`
					DefRebs   int     `json:"defRebs"`
					Fga       int     `json:"fga"`
					Fgm       int     `json:"fgm"`
					Fgpct     float64 `json:"fgpct"`
					Fouls     int     `json:"fouls"`
					Fta       int     `json:"fta"`
					Ftm       int     `json:"ftm"`
					Ftpct     float64 `json:"ftpct"`
					Mins      int     `json:"mins"`
					OffRebs   int     `json:"offRebs"`
					Points    int     `json:"points"`
					Rebs      int     `json:"rebs"`
					Secs      int     `json:"secs"`
					Steals    int     `json:"steals"`
					Tpa       int     `json:"tpa"`
					Tpm       int     `json:"tpm"`
					Tppct     float64 `json:"tppct"`
					Turnovers int     `json:"turnovers"`
				} `json:"statTotal"`
			} `json:"pointGameLeader"`
			AssistGameLeader struct {
				Profile struct {
					Code               string `json:"code"`
					Country            string `json:"country"`
					DisplayAffiliation string `json:"displayAffiliation"`
					DisplayName        string `json:"displayName"`
					DisplayNameEn      string `json:"displayNameEn"`
					Dob                string `json:"dob"`
					DraftYear          string `json:"draftYear"`
					Experience         string `json:"experience"`
					FirstInitial       string `json:"firstInitial"`
					FirstName          string `json:"firstName"`
					FirstNameEn        string `json:"firstNameEn"`
					Height             string `json:"height"`
					JerseyNo           string `json:"jerseyNo"`
					LastName           string `json:"lastName"`
					LastNameEn         string `json:"lastNameEn"`
					LeagueID           string `json:"leagueId"`
					PlayerID           string `json:"playerId"`
					Position           string `json:"position"`
					SchoolType         string `json:"schoolType"`
					Weight             string `json:"weight"`
				} `json:"profile"`
				StatTotal struct {
					Assists   int     `json:"assists"`
					Blocks    int     `json:"blocks"`
					DefRebs   int     `json:"defRebs"`
					Fga       int     `json:"fga"`
					Fgm       int     `json:"fgm"`
					Fgpct     float64 `json:"fgpct"`
					Fouls     int     `json:"fouls"`
					Fta       int     `json:"fta"`
					Ftm       int     `json:"ftm"`
					Ftpct     float64 `json:"ftpct"`
					Mins      int     `json:"mins"`
					OffRebs   int     `json:"offRebs"`
					Points    int     `json:"points"`
					Rebs      int     `json:"rebs"`
					Secs      int     `json:"secs"`
					Steals    int     `json:"steals"`
					Tpa       int     `json:"tpa"`
					Tpm       int     `json:"tpm"`
					Tppct     float64 `json:"tppct"`
					Turnovers int     `json:"turnovers"`
				} `json:"statTotal"`
			} `json:"assistGameLeader"`
			ReboundGameLeader struct {
				Profile struct {
					Code               string `json:"code"`
					Country            string `json:"country"`
					DisplayAffiliation string `json:"displayAffiliation"`
					DisplayName        string `json:"displayName"`
					DisplayNameEn      string `json:"displayNameEn"`
					Dob                string `json:"dob"`
					DraftYear          string `json:"draftYear"`
					Experience         string `json:"experience"`
					FirstInitial       string `json:"firstInitial"`
					FirstName          string `json:"firstName"`
					FirstNameEn        string `json:"firstNameEn"`
					Height             string `json:"height"`
					JerseyNo           string `json:"jerseyNo"`
					LastName           string `json:"lastName"`
					LastNameEn         string `json:"lastNameEn"`
					LeagueID           string `json:"leagueId"`
					PlayerID           string `json:"playerId"`
					Position           string `json:"position"`
					SchoolType         string `json:"schoolType"`
					Weight             string `json:"weight"`
				} `json:"profile"`
				StatTotal struct {
					Assists   int     `json:"assists"`
					Blocks    int     `json:"blocks"`
					DefRebs   int     `json:"defRebs"`
					Fga       int     `json:"fga"`
					Fgm       int     `json:"fgm"`
					Fgpct     float64 `json:"fgpct"`
					Fouls     int     `json:"fouls"`
					Fta       int     `json:"fta"`
					Ftm       int     `json:"ftm"`
					Ftpct     float64 `json:"ftpct"`
					Mins      int     `json:"mins"`
					OffRebs   int     `json:"offRebs"`
					Points    int     `json:"points"`
					Rebs      int     `json:"rebs"`
					Secs      int     `json:"secs"`
					Steals    int     `json:"steals"`
					Tpa       int     `json:"tpa"`
					Tpm       int     `json:"tpm"`
					Tppct     float64 `json:"tppct"`
					Turnovers int     `json:"turnovers"`
				} `json:"statTotal"`
			} `json:"reboundGameLeader"`
			PointSeasonLeader struct {
				Profile struct {
					Code               string `json:"code"`
					Country            string `json:"country"`
					DisplayAffiliation string `json:"displayAffiliation"`
					DisplayName        string `json:"displayName"`
					DisplayNameEn      string `json:"displayNameEn"`
					Dob                string `json:"dob"`
					DraftYear          string `json:"draftYear"`
					Experience         string `json:"experience"`
					FirstInitial       string `json:"firstInitial"`
					FirstName          string `json:"firstName"`
					FirstNameEn        string `json:"firstNameEn"`
					Height             string `json:"height"`
					JerseyNo           string `json:"jerseyNo"`
					LastName           string `json:"lastName"`
					LastNameEn         string `json:"lastNameEn"`
					LeagueID           string `json:"leagueId"`
					PlayerID           string `json:"playerId"`
					Position           string `json:"position"`
					SchoolType         string `json:"schoolType"`
					Weight             string `json:"weight"`
				} `json:"profile"`
				StatAverage struct {
					AssistsPg    float64 `json:"assistsPg"`
					BlocksPg     float64 `json:"blocksPg"`
					DefRebsPg    float64 `json:"defRebsPg"`
					Efficiency   float64 `json:"efficiency"`
					FgaPg        float64 `json:"fgaPg"`
					FgmPg        float64 `json:"fgmPg"`
					Fgpct        float64 `json:"fgpct"`
					FoulsPg      float64 `json:"foulsPg"`
					FtaPg        float64 `json:"ftaPg"`
					FtmPg        float64 `json:"ftmPg"`
					Ftpct        float64 `json:"ftpct"`
					Games        int     `json:"games"`
					GamesStarted int     `json:"gamesStarted"`
					MinsPg       float64 `json:"minsPg"`
					OffRebsPg    float64 `json:"offRebsPg"`
					PointsPg     float64 `json:"pointsPg"`
					RebsPg       float64 `json:"rebsPg"`
					StealsPg     float64 `json:"stealsPg"`
					TpaPg        float64 `json:"tpaPg"`
					TpmPg        float64 `json:"tpmPg"`
					Tppct        float64 `json:"tppct"`
					TurnoversPg  float64 `json:"turnoversPg"`
				} `json:"statAverage"`
			} `json:"pointSeasonLeader"`
			AssistSeasonLeader struct {
				Profile struct {
					Code               string `json:"code"`
					Country            string `json:"country"`
					DisplayAffiliation string `json:"displayAffiliation"`
					DisplayName        string `json:"displayName"`
					DisplayNameEn      string `json:"displayNameEn"`
					Dob                string `json:"dob"`
					DraftYear          string `json:"draftYear"`
					Experience         string `json:"experience"`
					FirstInitial       string `json:"firstInitial"`
					FirstName          string `json:"firstName"`
					FirstNameEn        string `json:"firstNameEn"`
					Height             string `json:"height"`
					JerseyNo           string `json:"jerseyNo"`
					LastName           string `json:"lastName"`
					LastNameEn         string `json:"lastNameEn"`
					LeagueID           string `json:"leagueId"`
					PlayerID           string `json:"playerId"`
					Position           string `json:"position"`
					SchoolType         string `json:"schoolType"`
					Weight             string `json:"weight"`
				} `json:"profile"`
				StatAverage struct {
					AssistsPg    float64 `json:"assistsPg"`
					BlocksPg     float64 `json:"blocksPg"`
					DefRebsPg    float64 `json:"defRebsPg"`
					Efficiency   float64 `json:"efficiency"`
					FgaPg        float64 `json:"fgaPg"`
					FgmPg        float64 `json:"fgmPg"`
					Fgpct        float64 `json:"fgpct"`
					FoulsPg      float64 `json:"foulsPg"`
					FtaPg        float64 `json:"ftaPg"`
					FtmPg        float64 `json:"ftmPg"`
					Ftpct        float64 `json:"ftpct"`
					Games        int     `json:"games"`
					GamesStarted int     `json:"gamesStarted"`
					MinsPg       float64 `json:"minsPg"`
					OffRebsPg    float64 `json:"offRebsPg"`
					PointsPg     float64 `json:"pointsPg"`
					RebsPg       float64 `json:"rebsPg"`
					StealsPg     float64 `json:"stealsPg"`
					TpaPg        float64 `json:"tpaPg"`
					TpmPg        float64 `json:"tpmPg"`
					Tppct        float64 `json:"tppct"`
					TurnoversPg  float64 `json:"turnoversPg"`
				} `json:"statAverage"`
			} `json:"assistSeasonLeader"`
			ReboundSeasonLeader struct {
				Profile struct {
					Code               string `json:"code"`
					Country            string `json:"country"`
					DisplayAffiliation string `json:"displayAffiliation"`
					DisplayName        string `json:"displayName"`
					DisplayNameEn      string `json:"displayNameEn"`
					Dob                string `json:"dob"`
					DraftYear          string `json:"draftYear"`
					Experience         string `json:"experience"`
					FirstInitial       string `json:"firstInitial"`
					FirstName          string `json:"firstName"`
					FirstNameEn        string `json:"firstNameEn"`
					Height             string `json:"height"`
					JerseyNo           string `json:"jerseyNo"`
					LastName           string `json:"lastName"`
					LastNameEn         string `json:"lastNameEn"`
					LeagueID           string `json:"leagueId"`
					PlayerID           string `json:"playerId"`
					Position           string `json:"position"`
					SchoolType         string `json:"schoolType"`
					Weight             string `json:"weight"`
				} `json:"profile"`
				StatAverage struct {
					AssistsPg    float64 `json:"assistsPg"`
					BlocksPg     float64 `json:"blocksPg"`
					DefRebsPg    float64 `json:"defRebsPg"`
					Efficiency   float64 `json:"efficiency"`
					FgaPg        float64 `json:"fgaPg"`
					FgmPg        float64 `json:"fgmPg"`
					Fgpct        float64 `json:"fgpct"`
					FoulsPg      float64 `json:"foulsPg"`
					FtaPg        float64 `json:"ftaPg"`
					FtmPg        float64 `json:"ftmPg"`
					Ftpct        float64 `json:"ftpct"`
					Games        int     `json:"games"`
					GamesStarted int     `json:"gamesStarted"`
					MinsPg       float64 `json:"minsPg"`
					OffRebsPg    float64 `json:"offRebsPg"`
					PointsPg     float64 `json:"pointsPg"`
					RebsPg       float64 `json:"rebsPg"`
					StealsPg     float64 `json:"stealsPg"`
					TpaPg        float64 `json:"tpaPg"`
					TpmPg        float64 `json:"tpmPg"`
					Tppct        float64 `json:"tppct"`
					TurnoversPg  float64 `json:"turnoversPg"`
				} `json:"statAverage"`
			} `json:"reboundSeasonLeader"`
		} `json:"awayTeam"`
	} `json:"payload"`
	Timestamp string `json:"timestamp"`
}

type ConferenceStanding struct {
	Context struct {
		User struct {
			CountryCode  string `json:"countryCode"`
			CountryName  string `json:"countryName"`
			Locale       string `json:"locale"`
			TimeZone     string `json:"timeZone"`
			TimeZoneCity string `json:"timeZoneCity"`
		} `json:"user"`
		Device struct {
			Clazz interface{} `json:"clazz"`
		} `json:"device"`
	} `json:"context"`
	Error struct {
		Detail  interface{} `json:"detail"`
		IsError string      `json:"isError"`
		Message interface{} `json:"message"`
	} `json:"error"`
	Payload struct {
		League struct {
			ID   string `json:"id"`
			Name string `json:"name"`
		} `json:"league"`
		Season struct {
			IsCurrent               string `json:"isCurrent"`
			RosterSeasonType        int    `json:"rosterSeasonType"`
			RosterSeasonYear        string `json:"rosterSeasonYear"`
			RosterSeasonYearDisplay string `json:"rosterSeasonYearDisplay"`
			ScheduleSeasonType      int    `json:"scheduleSeasonType"`
			ScheduleSeasonYear      string `json:"scheduleSeasonYear"`
			ScheduleYearDisplay     string `json:"scheduleYearDisplay"`
			StatsSeasonType         int    `json:"statsSeasonType"`
			StatsSeasonYear         string `json:"statsSeasonYear"`
			StatsSeasonYearDisplay  string `json:"statsSeasonYearDisplay"`
			Year                    string `json:"year"`
			YearDisplay             string `json:"yearDisplay"`
		} `json:"season"`
		StandingGroups []struct {
			Teams []struct {
				Profile struct {
					Abbr              string `json:"abbr"`
					City              string `json:"city"`
					CityEn            string `json:"cityEn"`
					Code              string `json:"code"`
					Conference        string `json:"conference"`
					DisplayAbbr       string `json:"displayAbbr"`
					DisplayConference string `json:"displayConference"`
					Division          string `json:"division"`
					ID                string `json:"id"`
					IsAllStarTeam     bool   `json:"isAllStarTeam"`
					IsLeagueTeam      bool   `json:"isLeagueTeam"`
					LeagueID          string `json:"leagueId"`
					Name              string `json:"name"`
					NameEn            string `json:"nameEn"`
				} `json:"profile"`
				Standings struct {
					AheadAtHalfLoss     string  `json:"aheadAtHalfLoss"`
					AheadAtHalfWin      string  `json:"aheadAtHalfWin"`
					AheadAtThirdLoss    string  `json:"aheadAtThirdLoss"`
					AheadAtThirdWin     string  `json:"aheadAtThirdWin"`
					BehindAtHalfLoss    string  `json:"behindAtHalfLoss"`
					BehindAtHalfWin     string  `json:"behindAtHalfWin"`
					BehindAtThirdLoss   string  `json:"behindAtThirdLoss"`
					BehindAtThirdWin    string  `json:"behindAtThirdWin"`
					Clinched            string  `json:"clinched"`
					ConfGamesBehind     float64 `json:"confGamesBehind"`
					ConfLoss            int     `json:"confLoss"`
					ConfRank            int     `json:"confRank"`
					ConfWin             int     `json:"confWin"`
					DivGameBehind       float64 `json:"divGameBehind"`
					DivLoss             int     `json:"divLoss"`
					DivRank             int     `json:"divRank"`
					DivWin              int     `json:"divWin"`
					FewerTurnoversLoss  string  `json:"fewerTurnoversLoss"`
					FewerTurnoversWin   string  `json:"fewerTurnoversWin"`
					HomeLoss            int     `json:"homeLoss"`
					HomeStreak          string  `json:"homeStreak"`
					HomeWin             int     `json:"homeWin"`
					Last10              string  `json:"last10"`
					Last10Home          string  `json:"last10Home"`
					Last10Road          string  `json:"last10Road"`
					LeadInFgpctloss     string  `json:"leadInFgpctloss"`
					LeadInFgpctwin      string  `json:"leadInFgpctwin"`
					LeadInRebLoss       string  `json:"leadInRebLoss"`
					LeadInRebWin        string  `json:"leadInRebWin"`
					LoseStreak          string  `json:"loseStreak"`
					Losses              int     `json:"losses"`
					OnHotStreak         string  `json:"onHotStreak"`
					Oppover500Loss      string  `json:"oppover500Loss"`
					Oppover500Win       string  `json:"oppover500Win"`
					Oppscore100PlusLoss string  `json:"oppscore100PlusLoss"`
					Oppscore100PlusWin  string  `json:"oppscore100PlusWin"`
					Otloss              string  `json:"otloss"`
					Otwin               string  `json:"otwin"`
					PointsAgainst       float64 `json:"pointsAgainst"`
					PointsDiff          float64 `json:"pointsDiff"`
					PointsFor           float64 `json:"pointsFor"`
					RoadLoss            int     `json:"roadLoss"`
					RoadStreak          string  `json:"roadStreak"`
					RoadWin             int     `json:"roadWin"`
					Score100PlusLoss    string  `json:"score100PlusLoss"`
					Score100PlusWin     string  `json:"score100PlusWin"`
					Streak              string  `json:"streak"`
					TenPtsOrMoreLoss    string  `json:"tenPtsOrMoreLoss"`
					TenPtsOrMoreWin     string  `json:"tenPtsOrMoreWin"`
					ThreePtsOrLessLoss  string  `json:"threePtsOrLessLoss"`
					ThreePtsOrLessWin   string  `json:"threePtsOrLessWin"`
					TiedAtHalfLoss      string  `json:"tiedAtHalfLoss"`
					TiedAtHalfWin       string  `json:"tiedAtHalfWin"`
					TiedAtThirdLoss     string  `json:"tiedAtThirdLoss"`
					TiedAtThirdWin      string  `json:"tiedAtThirdWin"`
					WinPct              float64 `json:"winPct"`
					WinStreak           string  `json:"winStreak"`
					Wins                int     `json:"wins"`
				} `json:"standings"`
			} `json:"teams"`
			Conference        string      `json:"conference"`
			DisplayConference string      `json:"displayConference"`
			DisplayDivision   interface{} `json:"displayDivision"`
			Division          interface{} `json:"division"`
		} `json:"standingGroups"`
		Grouping string `json:"grouping"`
	} `json:"payload"`
	Timestamp string `json:"timestamp"`
}
